### PR TITLE
Qifeid/wca dev

### PR DESCRIPTION
**Pull request by T0ny8576**
Add new options and features for GatedTwoStageProcessor

### CODE REVIEW

**Review by akindofyoga — COMMENTED** [review]
This looks fine. However, could you remove all of the changes to whitespace?

**Comment by T0ny8576** [comment]
> This looks fine. However, could you remove all of the changes to whitespace?

I have removed all of the auto-inserted whitespaces inside `gabrieltool/statemachine-editor-react/src/diagram.js`. In `gabrieltool/statemachine-editor-react/src/processor-zoo.json`, I changed two tabs to whitespaces to make the file indentation consistent. Does it look good now?

**Comment by akindofyoga** [comment]
Could you just add the newline back to the end of `gabrieltool/statemachine-editor-react/src/processor-zoo.json`? Everything else looks good

**Comment by T0ny8576** [comment]
Sure. I've made the changes.

**Pull request merged**
